version: '3'
services:

  cqcmp-mysql:
    image: "mysql:latest"
    container_name: cqcmp-mysql
    volumes:
      - /home/priyanko-ubuntu-20/Desktop/dockerCompose/init.sql:/docker-entrypoint-initdb.d/init-script.sql
      - mysql-data:/var/lib/mysql3/data
    ports:
      - 3307:3306
    environment:
      - MYSQL_DB:CQCMP
      - MYSQL_USER:cqcmp_user
      - MYSQL_PASSWORD:cqcmp_password
      - MYSQL_ROOT_PASSWORD=password

  cqcmp-app:
    image: "priyanko27/cqcmp:latest"
    container_name: cqcmp-app
    environment:
      - DB_SERVER=cqcmp-mysql
    ports:
      - 8102:8095
#    depends_on:
#      cqcmp-mysql:
#        condition: service_started

  cqcmp-ui:
    image: "priyanko27/cqcmp_fe:latest"
    container_name: cqcmp-ui
    ports:
      - 4200:3000
    links:
      - cqcmp-app


volumes:
  mysql-data: