version: '3'
services:

  cqcmp-mysql2:
    image: "mysql:latest"
    container_name: cqcmp-mysql2
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init-script.sql
      - mysql-data:/var/lib/mysql/data2
    ports:
      - 3306:3306
    environment:
      - MYSQL_DB:CQCMP
      - MYSQL_USER:cqcmp_user
      - MYSQL_PASSWORD:cqcmp_password
      - MYSQL_ROOT_PASSWORD: password

  cqcmp-app2:
    image: "priyanko27/cqcmp:latest"
    container_name: cqcmp-app2
    environment:
      - DB_SERVER=cqcmp-mysql2
    ports:
      - 8095:8095
    links:
      - cqcmp-mysql2

  #kanban-ui:
  #  build: ./kanban-ui
  #  container_name: kanban-ui
  #  ports:
   #   - 4200:80
  #  links:
   #   - kanban-app


volumes:
  mysql-data: